/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package mygroovy.app

import mygroovy.list.LinkedList

import static mygroovy.utilities.StringUtils.join
import static mygroovy.utilities.StringUtils.split
import static mygroovy.app.MessageUtils.getMessage

import org.apache.commons.text.WordUtils

class App {
    static void main(String[] args) {
        LinkedList tokens
        tokens = split(getMessage())
        String result = join(tokens)
        println(WordUtils.capitalize(result))
    }
}
